NODEJS_EXTRA_4 = [
    {"question_text": "What is the output?\n\nconsole.log(Math.sign(0));", "option_a": "0", "option_b": "1", "option_c": "-1", "option_d": "NaN", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number.parseFloat('3.14abc'));", "option_a": "NaN", "option_b": "3.14", "option_c": "3", "option_d": "'3.14abc'", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('abc'.repeat(3));", "option_a": "'abc3'", "option_b": "['abc','abc','abc']", "option_c": "'abcabcabc'", "option_d": "9", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(null == undefined);", "option_a": "false", "option_b": "null", "option_c": "undefined", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(null === undefined);", "option_a": "false", "option_b": "true", "option_c": "null", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(!null);", "option_a": "null", "option_b": "true", "option_c": "false", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(+'42');", "option_a": "'42'", "option_b": "NaN", "option_c": "42", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(typeof function(){});", "option_a": "object", "option_b": "class", "option_c": "undefined", "option_d": "function", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(1 + '1' - 1);", "option_a": "10", "option_b": "1", "option_c": "'10'", "option_d": "NaN", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1].length + [].length);", "option_a": "0", "option_b": "1", "option_c": "2", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.match(/l/g));", "option_a": "['l']", "option_b": "2", "option_c": "['l', 'l']", "option_d": "'ll'", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([...[1, 2], ...[3, 4]]);", "option_a": "[[1,2],[3,4]]", "option_b": "[1,2]", "option_c": "[3,4]", "option_d": "[1, 2, 3, 4]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(String(undefined));", "option_a": "'undefined'", "option_b": "undefined", "option_c": "''", "option_d": "null", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number(true));", "option_a": "true", "option_b": "1", "option_c": "0", "option_d": "NaN", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Number(false));", "option_a": "1", "option_b": "false", "option_c": "0", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Number(null));", "option_a": "NaN", "option_b": "null", "option_c": "1", "option_d": "0", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Number(undefined));", "option_a": "NaN", "option_b": "0", "option_c": "undefined", "option_d": "null", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Math.hypot(3, 4));", "option_a": "7", "option_b": "5", "option_c": "12", "option_d": "25", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('a' < 'b');", "option_a": "false", "option_b": "'a'", "option_c": "true", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(2 ** 3 ** 2);", "option_a": "64", "option_b": "512", "option_c": "18", "option_d": "512", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconst fn = () => 42;\nconsole.log(fn());", "option_a": "42", "option_b": "undefined", "option_c": "() => 42", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].map(x => x * 2));", "option_a": "[1,2,3]", "option_b": "[2, 4, 6]", "option_c": "12", "option_d": "[2]", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].filter(x => x % 2 !== 0));", "option_a": "[2]", "option_b": "[1,2,3]", "option_c": "[1, 3]", "option_d": "[]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Object.assign({}, {a: 1}, {b: 2}));", "option_a": "{a:1}", "option_b": "{b:2}", "option_c": "{}", "option_d": "{a: 1, b: 2}", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].reduceRight((acc, cur) => acc + cur, ''));", "option_a": "'321'", "option_b": "'123'", "option_c": "6", "option_d": "'6'", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(typeof 42n);", "option_a": "number", "option_b": "bigint", "option_c": "integer", "option_d": "object", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.cbrt(27));", "option_a": "9", "option_b": "27", "option_c": "3", "option_d": "729", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconst [a,,b] = [1, 2, 3];\nconsole.log(b);", "option_a": "2", "option_b": "1", "option_c": "undefined", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log({a: 1, b: 2, c: 3} instanceof Object);", "option_a": "true", "option_b": "false", "option_c": "Object", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3] instanceof Array);", "option_a": "false", "option_b": "true", "option_c": "Array", "option_d": "Error", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('hello world'.split(' ').length);", "option_a": "11", "option_b": "1", "option_c": "2", "option_d": "5", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.startsWith('hel'));", "option_a": "false", "option_b": "'hel'", "option_c": "3", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.endsWith('llo'));", "option_a": "true", "option_b": "false", "option_c": "'llo'", "option_d": "3", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(String.raw`hello\\nworld`);", "option_a": "hello\\nworld (no newline)", "option_b": "hello\nworld", "option_c": "Error", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Math.log2(8));", "option_a": "2", "option_b": "3", "option_c": "8", "option_d": "256", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.log10(1000));", "option_a": "10", "option_b": "100", "option_c": "3", "option_d": "1000", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(([1]+[2]).length);", "option_a": "2", "option_b": "1", "option_c": "3", "option_d": "3", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(!!'false');", "option_a": "false", "option_b": "'false'", "option_c": "0", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(!!'');", "option_a": "false", "option_b": "true", "option_c": "''", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(!!0);", "option_a": "0", "option_b": "false", "option_c": "true", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.fround(1.337));", "option_a": "1", "option_b": "1.34", "option_c": "1.3370000123977661", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "Which method creates a promise that resolves when all input promises resolve?", "option_a": "Promise.race", "option_b": "Promise.any", "option_c": "Promise.allSettled", "option_d": "Promise.all", "correct_option": "D"},
    {"question_text": "Which method returns the first settled (resolved or rejected) promise?", "option_a": "Promise.race", "option_b": "Promise.all", "option_c": "Promise.allSettled", "option_d": "Promise.any", "correct_option": "A"},
    {"question_text": "Which method returns the first FULFILLED promise (ignoring rejections)?", "option_a": "Promise.all", "option_b": "Promise.any", "option_c": "Promise.race", "option_d": "Promise.allSettled", "correct_option": "B"},
    {"question_text": "Which method waits for ALL promises to settle (resolve or reject)?", "option_a": "Promise.all", "option_b": "Promise.race", "option_c": "Promise.allSettled", "option_d": "Promise.any", "correct_option": "C"},
    {"question_text": "What does the optional chaining operator (?.) return if the property doesn't exist?", "option_a": "null", "option_b": "false", "option_c": "0", "option_d": "undefined", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(null ?? 'default');", "option_a": "'default'", "option_b": "null", "option_c": "undefined", "option_d": "false", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(0 ?? 'default');", "option_a": "'default'", "option_b": "0", "option_c": "false", "option_d": "null", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(0 || 'default');", "option_a": "0", "option_b": "false", "option_c": "'default'", "option_d": "null", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('' ?? 'default');", "option_a": "'default'", "option_b": "null", "option_c": "undefined", "option_d": "''", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(new WeakMap().has({}));", "option_a": "false", "option_b": "true", "option_c": "undefined", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([...new Set([1,1,2,2,3])]);", "option_a": "[1,1,2,2,3]", "option_b": "[1, 2, 3]", "option_c": "Set(3)", "option_d": "5", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.keys({}).length);", "option_a": "undefined", "option_b": "null", "option_c": "0", "option_d": "1", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Array.from({length: 3}, (_, i) => i));", "option_a": "[undefined, undefined, undefined]", "option_b": "[3]", "option_c": "{length:3}", "option_d": "[0, 1, 2]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(1 + null);", "option_a": "1", "option_b": "null", "option_c": "NaN", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(1 + undefined);", "option_a": "1", "option_b": "NaN", "option_c": "undefined", "option_d": "null", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('10' - 5);", "option_a": "'105'", "option_b": "'5'", "option_c": "5", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('10' * 2);", "option_a": "'1010'", "option_b": "'20'", "option_c": "NaN", "option_d": "20", "correct_option": "D"},
]
