NODEJS_EXTRA_3 = [
    {"question_text": "What is the output?\n\nconsole.log(['a', 'b', 'c'].find(x => x === 'b'));", "option_a": "'b'", "option_b": "1", "option_c": "true", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(['a', 'b', 'c'].findIndex(x => x === 'c'));", "option_a": "'c'", "option_b": "2", "option_c": "3", "option_d": "-1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].every(x => x > 0));", "option_a": "false", "option_b": "[1,2,3]", "option_c": "true", "option_d": "3", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([1, -1, 3].every(x => x > 0));", "option_a": "true", "option_b": "3", "option_c": "[1,3]", "option_d": "false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].some(x => x > 2));", "option_a": "true", "option_b": "false", "option_c": "3", "option_d": "[3]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].reduce((acc, cur) => acc + cur, 0));", "option_a": "0", "option_b": "6", "option_c": "[1,2,3]", "option_d": "3", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.entries({a: 1, b: 2}));", "option_a": "{a:1,b:2}", "option_b": "['a','b']", "option_c": "[['a', 1], ['b', 2]]", "option_d": "[1, 2]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Object.values({a: 1, b: 2}));", "option_a": "['a','b']", "option_b": "{1,2}", "option_c": "[['a',1],['b',2]]", "option_d": "[1, 2]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Object.fromEntries([['a', 1], ['b', 2]]));", "option_a": "{a: 1, b: 2}", "option_b": "[['a',1],['b',2]]", "option_c": "Map", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(typeof undefined);", "option_a": "null", "option_b": "undefined", "option_c": "object", "option_d": "void", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(2 ** 10);", "option_a": "20", "option_b": "100", "option_c": "1024", "option_d": "210", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isInteger(1.0));", "option_a": "false", "option_b": "1.0", "option_c": "NaN", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(typeof NaN);", "option_a": "number", "option_b": "NaN", "option_c": "undefined", "option_d": "object", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(NaN === NaN);", "option_a": "true", "option_b": "false", "option_c": "NaN", "option_d": "Error", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.is(NaN, NaN));", "option_a": "false", "option_b": "NaN", "option_c": "true", "option_d": "Error", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(0 === -0);", "option_a": "false", "option_b": "0", "option_c": "NaN", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Object.is(0, -0));", "option_a": "false", "option_b": "true", "option_c": "0", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([...'hello'].length);", "option_a": "1", "option_b": "5", "option_c": "'hello'", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(typeof Symbol('test'));", "option_a": "string", "option_b": "object", "option_c": "symbol", "option_d": "Symbol", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].flat(0));", "option_a": "[]", "option_b": "[1,2,3]", "option_c": "0", "option_d": "[1, 2, 3]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].at(-1));", "option_a": "3", "option_b": "-1", "option_c": "1", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.at(-1));", "option_a": "h", "option_b": "o", "option_c": "-1", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(structuredClone({a: 1}).a);", "option_a": "undefined", "option_b": "{a:1}", "option_c": "1", "option_d": "Error", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Number.MAX_SAFE_INTEGER === 2**53 - 1);", "option_a": "false", "option_b": "NaN", "option_c": "undefined", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(globalThis === global);", "option_a": "true (in Node.js)", "option_b": "false", "option_c": "Error", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Symbol.for('a') === Symbol.for('a'));", "option_a": "false", "option_b": "true", "option_c": "Error", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Symbol('a') === Symbol('a'));", "option_a": "true", "option_b": "Symbol(a)", "option_c": "false", "option_d": "Error", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(typeof BigInt(42));", "option_a": "number", "option_b": "integer", "option_c": "object", "option_d": "bigint", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(JSON.parse('{\"a\":1}').a);", "option_a": "1", "option_b": "a", "option_c": "undefined", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].includes(2));", "option_a": "2", "option_b": "true", "option_c": "1", "option_d": "false", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.padStart(8, '*'));", "option_a": "hello***", "option_b": "***hello***", "option_c": "***hello", "option_d": "*hello", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.padEnd(8, '*'));", "option_a": "***hello", "option_b": "*hello*", "option_c": "hello**", "option_d": "hello***", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('  hello  '.trimStart());", "option_a": "'hello  '", "option_b": "'  hello'", "option_c": "'hello'", "option_d": "'  hello  '", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log('  hello  '.trimEnd());", "option_a": "'hello  '", "option_b": "'  hello'", "option_c": "'hello'", "option_d": "'  hello  '", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Array.isArray([]));", "option_a": "false", "option_b": "[]", "option_c": "true", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Array.isArray({}));", "option_a": "true", "option_b": "[]", "option_c": "undefined", "option_d": "false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isFinite(Infinity));", "option_a": "false", "option_b": "true", "option_c": "Infinity", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isFinite(42));", "option_a": "42", "option_b": "true", "option_c": "false", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.trunc(-4.7));", "option_a": "-5", "option_b": "-4.7", "option_c": "-4", "option_d": "4", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Math.sign(-42));", "option_a": "-42", "option_b": "0", "option_c": "42", "option_d": "-1", "correct_option": "D"},
]
