NODEJS_EXTRA_2 = [
    {"question_text": "What is the output?\n\nconsole.log(typeof null);", "option_a": "object", "option_b": "null", "option_c": "undefined", "option_d": "boolean", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].indexOf(4));", "option_a": "3", "option_b": "-1", "option_c": "undefined", "option_d": "null", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('5' + 3);", "option_a": "8", "option_b": "'35'", "option_c": "'53'", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([2, 1, 3].sort()[0]);", "option_a": "3", "option_b": "2", "option_c": "undefined", "option_d": "1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(!!'0');", "option_a": "true", "option_b": "false", "option_c": "'0'", "option_d": "0", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2].concat([3, 4]));", "option_a": "[[1,2],[3,4]]", "option_b": "[1, 2, 3, 4]", "option_c": "[1, 2]", "option_d": "6", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.keys({b: 2, a: 1})[0]);", "option_a": "a", "option_b": "2", "option_c": "b", "option_d": "1", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Math.floor(-3.1));", "option_a": "-3", "option_b": "-3.1", "option_c": "3", "option_d": "-4", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(JSON.stringify([1, undefined, 3]));", "option_a": "[1,null,3]", "option_b": "[1,undefined,3]", "option_c": "[1,3]", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.slice(1, 3));", "option_a": "hel", "option_b": "el", "option_c": "ell", "option_d": "he", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].splice(1, 1));", "option_a": "[1, 3]", "option_b": "[1, 2, 3]", "option_c": "[2]", "option_d": "1", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(typeof []);", "option_a": "array", "option_b": "list", "option_c": "undefined", "option_d": "object", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(new Map([['a', 1], ['b', 2]]).size);", "option_a": "2", "option_b": "4", "option_c": "1", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].pop());", "option_a": "[1, 2]", "option_b": "3", "option_c": "1", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(parseInt('123abc'));", "option_a": "NaN", "option_b": "'123abc'", "option_c": "123", "option_d": "0", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Object.freeze({a: 1}).a);", "option_a": "undefined", "option_b": "null", "option_c": "0", "option_d": "1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isNaN('hello'));", "option_a": "false", "option_b": "true", "option_c": "NaN", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([...'abc'].reverse().join(''));", "option_a": "abc", "option_b": "cba", "option_c": "['c','b','a']", "option_d": "Error", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.ceil(-2.3));", "option_a": "-3", "option_b": "-2.3", "option_c": "-2", "option_d": "2", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log({...{a: 1}, ...{a: 2}}.a);", "option_a": "1", "option_b": "undefined", "option_c": "[1, 2]", "option_d": "2", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, [2, [3]]].flat().length);", "option_a": "3", "option_b": "2", "option_c": "4", "option_d": "1", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.indexOf('ll'));", "option_a": "-1", "option_b": "2", "option_c": "3", "option_d": "1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].join('|'));", "option_a": "[1|2|3]", "option_b": "'123'", "option_c": "'1|2|3'", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(void 0 === undefined);", "option_a": "false", "option_b": "void", "option_c": "0", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('abc'.split('').reverse().join(''));", "option_a": "cba", "option_b": "abc", "option_c": "['c','b','a']", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(new Set('hello').size);", "option_a": "5", "option_b": "4", "option_c": "3", "option_d": "1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.min(1, -1, 0));", "option_a": "0", "option_b": "1", "option_c": "-1", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].shift());", "option_a": "[2, 3]", "option_b": "3", "option_c": "undefined", "option_d": "1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(String(null));", "option_a": "'null'", "option_b": "null", "option_c": "''", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2].unshift(0));", "option_a": "[0, 1, 2]", "option_b": "3", "option_c": "0", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Infinity + Infinity);", "option_a": "NaN", "option_b": "0", "option_c": "Infinity", "option_d": "Error", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Infinity - Infinity);", "option_a": "Infinity", "option_b": "0", "option_c": "Error", "option_d": "NaN", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Object.create(null).hasOwnProperty);", "option_a": "undefined", "option_b": "function", "option_c": "null", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([,,,].length);", "option_a": "0", "option_b": "3", "option_c": "4", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(+'');", "option_a": "NaN", "option_b": "''", "option_c": "0", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(typeof class {});", "option_a": "class", "option_b": "object", "option_c": "undefined", "option_d": "function", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('foo' in {foo: 'bar'});", "option_a": "true", "option_b": "false", "option_c": "'bar'", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].toString());", "option_a": "[1,2,3]", "option_b": "'1,2,3'", "option_c": "6", "option_d": "'[1,2,3]'", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(new Boolean(false) == false);", "option_a": "false", "option_b": "Error", "option_c": "true", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(new Boolean(false) === false);", "option_a": "true", "option_b": "undefined", "option_c": "Error", "option_d": "false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1].concat([2], [3]));", "option_a": "[1, 2, 3]", "option_b": "[[1],[2],[3]]", "option_c": "6", "option_d": "[1, [2], [3]]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Math.pow(2, 0));", "option_a": "2", "option_b": "1", "option_c": "0", "option_d": "NaN", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(isNaN('hello'));", "option_a": "false", "option_b": "'hello'", "option_c": "true", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Array.from('abc'));", "option_a": "['abc']", "option_b": "3", "option_c": "'abc'", "option_d": "['a', 'b', 'c']", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(new Array(5).length);", "option_a": "5", "option_b": "0", "option_c": "undefined", "option_d": "1", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Math.abs(-0) === Math.abs(0));", "option_a": "false", "option_b": "true", "option_c": "0", "option_d": "NaN", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.replace(/l/g, 'L'));", "option_a": "heLlo", "option_b": "hello", "option_c": "heLLo", "option_d": "HELLO", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([3,1,2].sort((a,b) => b - a)[0]);", "option_a": "1", "option_b": "2", "option_c": "[3,2,1]", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3,4,5].slice(-2));", "option_a": "[4, 5]", "option_b": "[1, 2, 3]", "option_c": "[5]", "option_d": "[3, 4]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Map.groupBy === undefined);", "option_a": "true", "option_b": "false", "option_c": "Error", "option_d": "null", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(new Set([1,2,3]).has(2));", "option_a": "2", "option_b": "false", "option_c": "true", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(/^hello$/.test('hello'));", "option_a": "'hello'", "option_b": "0", "option_c": "false", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isSafeInteger(9007199254740992));", "option_a": "false", "option_b": "true", "option_c": "NaN", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].with(1, 'x'));", "option_a": "[1,2,3,'x']", "option_b": "[1, 'x', 3]", "option_c": "['x',2,3]", "option_d": "Error", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].toReversed());", "option_a": "[1,2,3]", "option_b": "undefined", "option_c": "[3, 2, 1]", "option_d": "Error", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([3,1,2].toSorted());", "option_a": "[3,1,2]", "option_b": "Error", "option_c": "undefined", "option_d": "[1, 2, 3]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Object.hasOwn({a: 1}, 'a'));", "option_a": "true", "option_b": "false", "option_c": "1", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(structuredClone(new Date()).getTime() > 0);", "option_a": "false", "option_b": "true", "option_c": "Error", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].toSpliced(1, 1));", "option_a": "[2]", "option_b": "[1,2,3]", "option_c": "[1, 3]", "option_d": "Error", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.replaceAll('l', 'r'));", "option_a": "herlo", "option_b": "hello", "option_c": "heLLo", "option_d": "herro", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(WeakRef !== undefined);", "option_a": "true", "option_b": "false", "option_c": "Error", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Error('test').message);", "option_a": "Error", "option_b": "'test'", "option_c": "undefined", "option_d": "null", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1,2,3].findLast(x => x < 3));", "option_a": "1", "option_b": "[1,2]", "option_c": "2", "option_d": "3", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(AbortController !== undefined);", "option_a": "false", "option_b": "undefined", "option_c": "Error", "option_d": "true", "correct_option": "D"},
]
