PYTHON_EXTRA_2 = [
    {"question_text": "What is the output?\n\nprint(all([True, True, False]))", "option_a": "True", "option_b": "False", "option_c": "None", "option_d": "[True, True, False]", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint({'a': 1} | {'b': 2})", "option_a": "{'a': 1, 'b': 2}", "option_b": "TypeError", "option_c": "{'a': 1}", "option_d": "{'b': 2}", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint((1, 2, 3) * 2)", "option_a": "(2, 4, 6)", "option_b": "(1, 2, 3, 1, 2, 3)", "option_c": "6", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(type(1 == 1))", "option_a": "<class 'int'>", "option_b": "True", "option_c": "<class 'bool'>", "option_d": "1", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint([0]*5)", "option_a": "[0]", "option_b": "00000", "option_c": "5", "option_d": "[0, 0, 0, 0, 0]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(10 == 10.0)", "option_a": "True", "option_b": "False", "option_c": "TypeError", "option_d": "10", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(len({'a': 1, 'b': 2, 'c': 3}))", "option_a": "6", "option_b": "3", "option_c": "2", "option_d": "9", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('abc'.isalpha())", "option_a": "False", "option_b": "abc", "option_c": "True", "option_d": "None", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(list(range(5, 0, -1)))", "option_a": "[0, 1, 2, 3, 4, 5]", "option_b": "[1, 2, 3, 4, 5]", "option_c": "[]", "option_d": "[5, 4, 3, 2, 1]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(min(5, 3, 8, 1, 4))", "option_a": "1", "option_b": "8", "option_c": "5", "option_d": "3", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(type(b'hello'))", "option_a": "str", "option_b": "<class 'bytes'>", "option_c": "bytearray", "option_d": "list", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('hello world'.capitalize())", "option_a": "HELLO WORLD", "option_b": "Hello World", "option_c": "Hello world", "option_d": "hELLO WORLD", "correct_option": "C"},
    {"question_text": "What is the output?\n\ndef f(a, b=[], c=None):\n    return type(b).__name__\nprint(f(1))", "option_a": "NoneType", "option_b": "int", "option_c": "tuple", "option_d": "list", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint({1, 2, 3}.issubset({1, 2, 3, 4}))", "option_a": "True", "option_b": "False", "option_c": "{1, 2, 3}", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('aAbBcC'.swapcase())", "option_a": "aabbcc", "option_b": "AaBbCc", "option_c": "AABBCC", "option_d": "aAbBcC", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(bool({}))", "option_a": "True", "option_b": "{}", "option_c": "False", "option_d": "None", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(tuple('hello'))", "option_a": "('hello',)", "option_b": "'hello'", "option_c": "['h','e','l','l','o']", "option_d": "('h', 'e', 'l', 'l', 'o')", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint([1, 2, 3][::-1])", "option_a": "[3, 2, 1]", "option_b": "[1, 2, 3]", "option_c": "[]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(3 not in [1, 2, 4])", "option_a": "False", "option_b": "True", "option_c": "3", "option_d": "None", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(int(True) + int(False))", "option_a": "2", "option_b": "TrueFalse", "option_c": "1", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(set() | {1, 2})", "option_a": "set()", "option_b": "TypeError", "option_c": "{1}", "option_d": "{1, 2}", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(\"hello\".rjust(10, '*'))", "option_a": "*****hello", "option_b": "hello*****", "option_c": "**hello***", "option_d": "hello", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint([x**2 for x in range(5)])", "option_a": "[1, 4, 9, 16, 25]", "option_b": "[0, 1, 4, 9, 16]", "option_c": "[0, 2, 4, 6, 8]", "option_d": "[1, 2, 3, 4, 5]", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('python'.partition('th'))", "option_a": "['py', 'th', 'on']", "option_b": "('py', 'on')", "option_c": "('py', 'th', 'on')", "option_d": "'py' 'th' 'on'", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(sum(i for i in range(1, 6) if i % 2 != 0))", "option_a": "6", "option_b": "15", "option_c": "10", "option_d": "9", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('hello world'.rfind('o'))", "option_a": "7", "option_b": "4", "option_c": "-1", "option_d": "2", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(set('aaa'))", "option_a": "{'aaa'}", "option_b": "{'a'}", "option_c": "set()", "option_d": "3", "correct_option": "B"},
    {"question_text": "What is the output?\n\nfrom collections import Counter\nprint(Counter('abracadabra').most_common(1))", "option_a": "{'a': 5}", "option_b": "5", "option_c": "[('a', 5)]", "option_d": "'a'", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(float('nan') == float('nan'))", "option_a": "True", "option_b": "nan", "option_c": "TypeError", "option_d": "False", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(list(zip('abc', '123')))", "option_a": "[('a', '1'), ('b', '2'), ('c', '3')]", "option_b": "['a1', 'b2', 'c3']", "option_c": "[('abc', '123')]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(type(lambda: None))", "option_a": "NoneType", "option_b": "<class 'function'>", "option_c": "lambda", "option_d": "callable", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(9 ** 0.5 == 3)", "option_a": "False", "option_b": "3.0", "option_c": "True", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nimport itertools\nprint(list(itertools.chain([1, 2], [3, 4])))", "option_a": "[[1,2],[3,4]]", "option_b": "[1, 2]", "option_c": "10", "option_d": "[1, 2, 3, 4]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('abcdef'.removeprefix('abc'))", "option_a": "def", "option_b": "abc", "option_c": "abcdef", "option_d": "AttributeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(dict(zip(['a','b','c'], [1,2,3])))", "option_a": "[('a',1),('b',2)]", "option_b": "{'a': 1, 'b': 2, 'c': 3}", "option_c": "{'a','b','c'}", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nfrom collections import defaultdict\nd = defaultdict(int)\nd['x'] += 1\nprint(d['x'])", "option_a": "0", "option_b": "KeyError", "option_c": "1", "option_d": "None", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint('Hello'.isascii())", "option_a": "False", "option_b": "'Hello'", "option_c": "None", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(max('apple', 'banana', key=len))", "option_a": "banana", "option_b": "apple", "option_c": "6", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint((-1) ** 0.5)", "option_a": "-1", "option_b": "(6.123233995736766e-17+1j)", "option_c": "1", "option_d": "ValueError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('hello'.removesuffix('lo'))", "option_a": "hello", "option_b": "lo", "option_c": "hel", "option_d": "AttributeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(sorted([3,1,2], reverse=True)[0])", "option_a": "1", "option_b": "2", "option_c": "[3,2,1]", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint({True: 'yes', 1: 'one', 1.0: 'float'})", "option_a": "{True: 'float'}", "option_b": "{True: 'yes', 1: 'one', 1.0: 'float'}", "option_c": "{1.0: 'float'}", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(list(map(lambda x: x.upper(), ['a','b','c'])))", "option_a": "['a','b','c']", "option_b": "['A', 'B', 'C']", "option_c": "ABC", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(next(iter({3: 'c', 1: 'a', 2: 'b'})))", "option_a": "1", "option_b": "'c'", "option_c": "3", "option_d": "('c', 3)", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(memoryview(b'abc')[0])", "option_a": "b'a'", "option_b": "'a'", "option_c": "0", "option_d": "97", "correct_option": "D"},
]
