PYTHON_EXTRA = [
    {"question_text": "What is the output?\n\nprint(type([]) is list)", "option_a": "True", "option_b": "False", "option_c": "list", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nx = [1, 2, 3]\nprint(x[-1])", "option_a": "1", "option_b": "3", "option_c": "IndexError", "option_d": "-1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(2 ** 10)", "option_a": "20", "option_b": "100", "option_c": "1024", "option_d": "210", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint('hello'[::-1])", "option_a": "hello", "option_b": "h", "option_c": "o", "option_d": "olleh", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(len({1, 1, 2, 2, 3}))", "option_a": "3", "option_b": "5", "option_c": "2", "option_d": "1", "correct_option": "A"},
    {"question_text": "What is the output?\n\nx = {'a': 1, 'b': 2}\nprint(x.get('c', 0))", "option_a": "None", "option_b": "0", "option_c": "KeyError", "option_d": "c", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list(range(0, 10, 3)))", "option_a": "[0, 1, 2, 3]", "option_b": "[3, 6, 9]", "option_c": "[0, 3, 6, 9]", "option_d": "[0, 10, 3]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(isinstance(True, int))", "option_a": "False", "option_b": "TypeError", "option_c": "None", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(sorted([3, 1, 4, 1, 5], reverse=True))", "option_a": "[5, 4, 3, 1, 1]", "option_b": "[1, 1, 3, 4, 5]", "option_c": "[5, 4, 3, 1]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('abc' * 3)", "option_a": "abc3", "option_b": "abcabcabc", "option_c": "aaa bbb ccc", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(sum([1, 2, 3], 10))", "option_a": "6", "option_b": "10", "option_c": "16", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint({1: 'a', 2: 'b'}.values())", "option_a": "['a', 'b']", "option_b": "{1, 2}", "option_c": "('a', 'b')", "option_d": "dict_values(['a', 'b'])", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint([x for x in range(10) if x % 3 == 0])", "option_a": "[0, 3, 6, 9]", "option_b": "[3, 6, 9]", "option_c": "[0, 1, 2]", "option_d": "[1, 4, 7]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(min('hello'))", "option_a": "h", "option_b": "e", "option_c": "o", "option_d": "l", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list(zip([1,2,3], ['a','b'])))", "option_a": "[(1,'a'),(2,'b'),(3,None)]", "option_b": "Error", "option_c": "[(1, 'a'), (2, 'b')]", "option_d": "[(1,2,3),('a','b')]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(type(()))", "option_a": "<class 'list'>", "option_b": "NoneType", "option_c": "<class 'set'>", "option_d": "<class 'tuple'>", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('Hello World'.split())", "option_a": "['Hello', 'World']", "option_b": "('Hello', 'World')", "option_c": "Hello World", "option_d": "[H,e,l,l,o,W,o,r,l,d]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(abs(-7.5))", "option_a": "-7.5", "option_b": "7.5", "option_c": "7", "option_d": "8", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list(enumerate(['a','b','c'])))", "option_a": "[('a',0),('b',1),('c',2)]", "option_b": "[0,1,2]", "option_c": "[(0, 'a'), (1, 'b'), (2, 'c')]", "option_d": "['a','b','c']", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(round(2.5))", "option_a": "3", "option_b": "2.5", "option_c": "2.0", "option_d": "2", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(''.join(['H','e','l','l','o']))", "option_a": "Hello", "option_b": "['H','e','l','l','o']", "option_c": "H e l l o", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint({**{'a':1}, **{'b':2}})", "option_a": "{'a':1,'b':2,'a':1}", "option_b": "{'a': 1, 'b': 2}", "option_c": "TypeError", "option_d": "{'b': 2}", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint([1,2,3] + [4,5])", "option_a": "[5, 7]", "option_b": "TypeError", "option_c": "[1, 2, 3, 4, 5]", "option_d": "[[1,2,3],[4,5]]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nfrom functools import reduce\nprint(reduce(lambda a,b: a*b, [1,2,3,4]))", "option_a": "10", "option_b": "4", "option_c": "1234", "option_d": "24", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(max([1,2,3], key=lambda x: -x))", "option_a": "1", "option_b": "3", "option_c": "-1", "option_d": "-3", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(dict.fromkeys(['a','b','c'], 0))", "option_a": "{'a': 'b': 'c': 0}", "option_b": "{'a': 0, 'b': 0, 'c': 0}", "option_c": "[('a',0),('b',0)]", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list(filter(None, [0, 1, '', 'a', None, True])))", "option_a": "[0, 1, '', 'a']", "option_b": "[None, 0, '']", "option_c": "[1, 'a', True]", "option_d": "[0, None, '']", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(set('aabbcc'))", "option_a": "{'aabbcc'}", "option_b": "{'a','b','c','a','b','c'}", "option_c": "set()", "option_d": "{'a', 'b', 'c'}", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('Python'.find('th'))", "option_a": "2", "option_b": "3", "option_c": "-1", "option_d": "True", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(list(map(str, [1, 2, 3])))", "option_a": "[1, 2, 3]", "option_b": "['1', '2', '3']", "option_c": "'123'", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(divmod(17, 5))", "option_a": "3.4", "option_b": "(5, 17)", "option_c": "(3, 2)", "option_d": "2", "correct_option": "C"},
    {"question_text": "What is the output?\n\nx = [1, [2, 3]]\ny = x.copy()\ny[1].append(4)\nprint(x)", "option_a": "[1, [2, 3]]", "option_b": "[1, [2, 3, 4], 4]", "option_c": "[1, [2, 3], 4]", "option_d": "[1, [2, 3, 4]]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('hello'.center(11, '-'))", "option_a": "---hello---", "option_b": "hello------", "option_c": "---hello", "option_d": "hello", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(bin(10))", "option_a": "10", "option_b": "0b1010", "option_c": "1010", "option_d": "0x10", "correct_option": "B"},
    {"question_text": "What is the output?\n\nx = (1,)\nprint(type(x))", "option_a": "<class 'int'>", "option_b": "tuple", "option_c": "<class 'tuple'>", "option_d": "<class 'list'>", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint('hello world'.title())", "option_a": "Hello world", "option_b": "HELLO WORLD", "option_c": "hello world", "option_d": "Hello World", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(frozenset({1,2,3}) | frozenset({3,4,5}))", "option_a": "frozenset({1, 2, 3, 4, 5})", "option_b": "frozenset({3})", "option_c": "{1,2,3,4,5}", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(chr(65))", "option_a": "65", "option_b": "A", "option_c": "a", "option_d": "0x41", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint([i for i in range(5) for j in range(i) if j == 0])", "option_a": "[0, 1, 2, 3, 4]", "option_b": "[0, 0, 0, 0]", "option_c": "[1, 2, 3, 4]", "option_d": "[]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nimport sys\nprint(sys.getsizeof([]) < sys.getsizeof({}))", "option_a": "False", "option_b": "None", "option_c": "TypeError", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('abcdef'[1:5:2])", "option_a": "bd", "option_b": "bc", "option_c": "bce", "option_d": "abcd", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(hex(255))", "option_a": "255", "option_b": "0xff", "option_c": "ff", "option_d": "FF", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(any([0, 0, 0, 1]))", "option_a": "False", "option_b": "0", "option_c": "True", "option_d": "1", "correct_option": "C"},
    {"question_text": "What is the output?\n\ndef f(x, *args, **kwargs):\n    return len(args) + len(kwargs)\nprint(f(1, 2, 3, a=4, b=5))", "option_a": "5", "option_b": "3", "option_c": "2", "option_d": "4", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(list(reversed([1, 2, 3])))", "option_a": "[3, 2, 1]", "option_b": "[1, 2, 3]", "option_c": "reversed object", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('Hello'.ljust(10, '.'))", "option_a": ".....Hello", "option_b": "Hello.....", "option_c": "Hello", "option_d": "..Hello..", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(sorted('dcba'))", "option_a": "'abcd'", "option_b": "['d','c','b','a']", "option_c": "['a', 'b', 'c', 'd']", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(int('0b1010', 2))", "option_a": "1010", "option_b": "0b1010", "option_c": "2", "option_d": "10", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('python'.upper().isupper())", "option_a": "True", "option_b": "False", "option_c": "PYTHON", "option_d": "None", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint([1,2,3].index(2))", "option_a": "2", "option_b": "1", "option_c": "0", "option_d": "True", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(' '.join(str(i) for i in range(5)))", "option_a": "01234", "option_b": "[0,1,2,3,4]", "option_c": "0 1 2 3 4", "option_d": "0, 1, 2, 3, 4", "correct_option": "C"},
    {"question_text": "What is the output?\n\ns = {1, 2, 3}\ns.discard(5)\nprint(len(s))", "option_a": "KeyError", "option_b": "2", "option_c": "0", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(complex(3, 4).conjugate())", "option_a": "(3-4j)", "option_b": "(3+4j)", "option_c": "5.0", "option_d": "(4+3j)", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(list(dict.fromkeys([1,2,2,3,3,3])))", "option_a": "[1,2,2,3,3,3]", "option_b": "[1, 2, 3]", "option_c": "{1,2,3}", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint([None] * 3)", "option_a": "[None, None]", "option_b": "3", "option_c": "[None, None, None]", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint('a' in {'a': 1, 'b': 2})", "option_a": "False", "option_b": "1", "option_c": "KeyError", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(pow(2, 10, 100))", "option_a": "24", "option_b": "1024", "option_c": "100", "option_d": "10", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(list('abc'))", "option_a": "['abc']", "option_b": "['a', 'b', 'c']", "option_c": "abc", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint((lambda x, y: x + y)(3, 4))", "option_a": "34", "option_b": "lambda", "option_c": "7", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\na = [1, 2]\nb = [3, 4]\na.extend(b)\nprint(len(a), len(b))", "option_a": "2 2", "option_b": "4 0", "option_c": "2 4", "option_d": "4 2", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(hash((1, 2, 3)) == hash((1, 2, 3)))", "option_a": "True", "option_b": "False", "option_c": "TypeError", "option_d": "None", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('hello'.replace('l', 'L', 1))", "option_a": "heLLo", "option_b": "heLlo", "option_c": "HELLO", "option_d": "hello", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint({i: i**2 for i in range(4)})", "option_a": "{1:1, 2:4, 3:9}", "option_b": "[0, 1, 4, 9]", "option_c": "{0: 0, 1: 1, 2: 4, 3: 9}", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(10 // 3)", "option_a": "3.33", "option_b": "3.0", "option_c": "4", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('abc' > 'abd')", "option_a": "False", "option_b": "True", "option_c": "TypeError", "option_d": "None", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(str.maketrans('abc', '123'))", "option_a": "{'a':'1','b':'2','c':'3'}", "option_b": "{97: 49, 98: 50, 99: 51}", "option_c": "abc123", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(tuple(sorted({3, 1, 2})))", "option_a": "{1, 2, 3}", "option_b": "(3, 1, 2)", "option_c": "(1, 2, 3)", "option_d": "[1, 2, 3]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nclass A:\n    pass\nprint(bool(A()))", "option_a": "False", "option_b": "None", "option_c": "A", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('   hello   '.strip())", "option_a": "hello", "option_b": "   hello", "option_c": "hello   ", "option_d": "   hello   ", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(list(range(10, 0, -3)))", "option_a": "[10, 7, 4]", "option_b": "[10, 7, 4, 1]", "option_c": "[10, 8, 6, 4, 2]", "option_d": "[]", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(set([1,2]) & set([2,3]))", "option_a": "{1,2,3}", "option_b": "{1,3}", "option_c": "{2}", "option_d": "set()", "correct_option": "C"},
    {"question_text": "What is the output?\n\nx, *y, z = [1, 2, 3, 4, 5]\nprint(y)", "option_a": "[1, 2, 3]", "option_b": "(2, 3, 4)", "option_c": "3", "option_d": "[2, 3, 4]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(f'{42:08b}')", "option_a": "00101010", "option_b": "42", "option_c": "0b101010", "option_d": "101010", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(bytes(3))", "option_a": "b'3'", "option_b": "b'\\x00\\x00\\x00'", "option_c": "3", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint([1,2,3].pop(0))", "option_a": "3", "option_b": "[2,3]", "option_c": "1", "option_d": "[]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(None is None)", "option_a": "None", "option_b": "False", "option_c": "TypeError", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(ord('A'))", "option_a": "65", "option_b": "A", "option_c": "97", "option_d": "0x41", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('Hello\\nWorld'.count('l'))", "option_a": "1", "option_b": "3", "option_c": "2", "option_d": "4", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint({1,2,3} - {2,3,4})", "option_a": "{2,3}", "option_b": "{4}", "option_c": "{1}", "option_d": "set()", "correct_option": "C"},
    {"question_text": "What is the output?\n\nimport math\nprint(math.ceil(4.1))", "option_a": "4", "option_b": "4.1", "option_c": "4.0", "option_d": "5", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(bool([0]))", "option_a": "True", "option_b": "False", "option_c": "[0]", "option_d": "0", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(type(1j))", "option_a": "int", "option_b": "<class 'complex'>", "option_c": "float", "option_d": "imaginary", "correct_option": "B"},
    {"question_text": "What is the output?\n\na = [1, 2, 3]\na.insert(1, 'x')\nprint(a)", "option_a": "['x', 1, 2, 3]", "option_b": "[1, 2, 'x', 3]", "option_c": "[1, 'x', 2, 3]", "option_d": "[1, 2, 3, 'x']", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(hasattr([], 'append'))", "option_a": "False", "option_b": "'append'", "option_c": "None", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(id(256) == id(256))", "option_a": "True", "option_b": "False", "option_c": "256", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(str(123).zfill(6))", "option_a": "123000", "option_b": "000123", "option_c": "123   ", "option_d": "   123", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list({3:1, 1:2, 2:3}.keys()))", "option_a": "[1, 2, 3]", "option_b": "[1, 2, 3]", "option_c": "[3, 1, 2]", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(float('inf') > 10**100)", "option_a": "False", "option_b": "inf", "option_c": "OverflowError", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('hello'.startswith(('he', 'ha')))", "option_a": "True", "option_b": "False", "option_c": "'he'", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(sum(range(1, 11)))", "option_a": "10", "option_b": "55", "option_c": "45", "option_d": "100", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(' '.join(reversed('abc'.split())))", "option_a": "a b c", "option_b": "cba", "option_c": "abc", "option_d": "c b a", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(type(range(5)))", "option_a": "<class 'list'>", "option_b": "<class 'generator'>", "option_c": "<class 'tuple'>", "option_d": "<class 'range'>", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint([1,2,3,4,5][1::2])", "option_a": "[2, 4]", "option_b": "[1, 3, 5]", "option_c": "[2, 3]", "option_d": "[1, 2]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(len(range(0, 100, 7)))", "option_a": "100", "option_b": "15", "option_c": "14", "option_d": "7", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(type(None).__name__)", "option_a": "None", "option_b": "null", "option_c": "NoneType", "option_d": "type", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(2 in [1, [2, 3]])", "option_a": "True", "option_b": "[2,3]", "option_c": "2", "option_d": "False", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(eval('2 + 3 * 4'))", "option_a": "14", "option_b": "20", "option_c": "234", "option_d": "Error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('python'.count('o'))", "option_a": "0", "option_b": "1", "option_c": "2", "option_d": "None", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(max(1, 2, 3, key=lambda x: -x))", "option_a": "3", "option_b": "-1", "option_c": "1", "option_d": "-3", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(type({}))", "option_a": "<class 'set'>", "option_b": "set", "option_c": "empty", "option_d": "<class 'dict'>", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(len(b'hello'))", "option_a": "5", "option_b": "10", "option_c": "0", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(3 in range(1, 10, 2))", "option_a": "False", "option_b": "True", "option_c": "3", "option_d": "range(1,10,2)", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(oct(8))", "option_a": "8", "option_b": "08", "option_c": "0o10", "option_d": "10", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(isinstance([], (list, tuple)))", "option_a": "False", "option_b": "list", "option_c": "(list, tuple)", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('abc'.encode('utf-8'))", "option_a": "b'abc'", "option_b": "'abc'", "option_c": "[97,98,99]", "option_d": "abc", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(4 ** 0.5)", "option_a": "4", "option_b": "2.0", "option_c": "0.5", "option_d": "16", "correct_option": "B"},
    {"question_text": "What is the output?\n\nd = {'a': 1}\nd.setdefault('b', 2)\nprint(d)", "option_a": "{'a': 1}", "option_b": "{'b': 2}", "option_c": "{'a': 1, 'b': 2}", "option_d": "KeyError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(not not [])", "option_a": "True", "option_b": "[]", "option_c": "not", "option_d": "False", "correct_option": "D"},
]
