NODEJS_EXTRA = [
    {"question_text": "What is the output?\n\nconsole.log(typeof undefined);", "option_a": "undefined", "option_b": "null", "option_c": "object", "option_d": "string", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(0.1 + 0.2 === 0.3);", "option_a": "true", "option_b": "false", "option_c": "NaN", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(+'42');", "option_a": "'42'", "option_b": "NaN", "option_c": "42", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(null == undefined);\nconsole.log(null === undefined);", "option_a": "false false", "option_b": "true true", "option_c": "false true", "option_d": "true false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconst a = [1, 2, 3];\nconsole.log(a.includes(2));", "option_a": "true", "option_b": "false", "option_c": "1", "option_d": "2", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Math.max());", "option_a": "0", "option_b": "-Infinity", "option_c": "Infinity", "option_d": "NaN", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([...'hello']);", "option_a": "['hello']", "option_b": "'hello'", "option_c": "['h', 'e', 'l', 'l', 'o']", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(2 ** 3);", "option_a": "6", "option_b": "23", "option_c": "5", "option_d": "8", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(typeof NaN);", "option_a": "number", "option_b": "NaN", "option_c": "undefined", "option_d": "object", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconst obj = {a: 1};\nObject.freeze(obj);\nobj.a = 2;\nconsole.log(obj.a);", "option_a": "2", "option_b": "1", "option_c": "undefined", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].map(x => x * 2));", "option_a": "[1, 2, 3]", "option_b": "6", "option_c": "[2, 4, 6]", "option_d": "[1, 4, 9]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('10' - 5);", "option_a": "'105'", "option_b": "'5'", "option_c": "NaN", "option_d": "5", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].filter(x => x > 1).length);", "option_a": "2", "option_b": "3", "option_c": "1", "option_d": "[2, 3]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Boolean(''));", "option_a": "true", "option_b": "false", "option_c": "''", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.keys({a: 1, b: 2, c: 3}).length);", "option_a": "6", "option_b": "['a','b','c']", "option_c": "3", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Array.isArray([]));", "option_a": "false", "option_b": "'array'", "option_c": "undefined", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].reduce((a, b) => a + b, 0));", "option_a": "6", "option_b": "0", "option_c": "[1,2,3]", "option_d": "123", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(JSON.parse('{\"a\": 1}').a);", "option_a": "undefined", "option_b": "1", "option_c": "'{\"a\": 1}'", "option_d": "SyntaxError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([3, 1, 2].sort().join('-'));", "option_a": "3-1-2", "option_b": "321", "option_c": "1-2-3", "option_d": "1,2,3", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(typeof function(){});", "option_a": "object", "option_b": "undefined", "option_c": "null", "option_d": "function", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.padStart(8, '0'));", "option_a": "000hello", "option_b": "hello000", "option_c": "00hello0", "option_d": "hello", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(new Set([1, 1, 2, 2, 3]).size);", "option_a": "5", "option_b": "3", "option_c": "2", "option_d": "1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.entries({x: 10, y: 20}));", "option_a": "{x: 10, y: 20}", "option_b": "['x', 'y']", "option_c": "[['x', 10], ['y', 20]]", "option_d": "[10, 20]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].find(x => x > 1));", "option_a": "[2, 3]", "option_b": "1", "option_c": "true", "option_d": "2", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isInteger(1.0));", "option_a": "true", "option_b": "false", "option_c": "1", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].every(x => x > 0));", "option_a": "false", "option_b": "true", "option_c": "[1, 2, 3]", "option_d": "3", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Math.trunc(-4.7));", "option_a": "-5", "option_b": "4", "option_c": "-4", "option_d": "-4.7", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('abc'.repeat(2));", "option_a": "'abc2'", "option_b": "'aabbcc'", "option_c": "['abc','abc']", "option_d": "'abcabc'", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].flat());", "option_a": "[1, 2, 3]", "option_b": "6", "option_c": "[[1,2,3]]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number(''));", "option_a": "NaN", "option_b": "0", "option_c": "undefined", "option_d": "''", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.assign({}, {a: 1}, {b: 2}));", "option_a": "{a: 1}", "option_b": "{b: 2}", "option_c": "{a: 1, b: 2}", "option_d": "undefined", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.at(-1));", "option_a": "h", "option_b": "undefined", "option_c": "hello", "option_d": "o", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].some(x => x > 2));", "option_a": "true", "option_b": "false", "option_c": "3", "option_d": "[3]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(parseInt('0xF', 16));", "option_a": "0", "option_b": "15", "option_c": "16", "option_d": "NaN", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(structuredClone({a: 1, b: {c: 2}}));", "option_a": "undefined", "option_b": "null", "option_c": "{a: 1, b: {c: 2}}", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log([...[1, 2], ...[3, 4]]);", "option_a": "[[1,2],[3,4]]", "option_b": "10", "option_c": "[1,2,3]", "option_d": "[1, 2, 3, 4]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('Hello World'.startsWith('Hello'));", "option_a": "true", "option_b": "false", "option_c": "'Hello'", "option_d": "0", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Math.sign(-5));", "option_a": "5", "option_b": "-1", "option_c": "0", "option_d": "-5", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].findIndex(x => x === 2));", "option_a": "2", "option_b": "true", "option_c": "1", "option_d": "-1", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(globalThis === global);", "option_a": "false", "option_b": "undefined", "option_c": "TypeError", "option_d": "true", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, [2, [3]]].flat(Infinity));", "option_a": "[1, 2, 3]", "option_b": "[1, [2, [3]]]", "option_c": "[[1, 2, 3]]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Array.from({length: 3}, (_, i) => i));", "option_a": "[{}, {}, {}]", "option_b": "[0, 1, 2]", "option_c": "[undefined, undefined, undefined]", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.values({a: 1, b: 2}));", "option_a": "['a', 'b']", "option_b": "{a: 1, b: 2}", "option_c": "[1, 2]", "option_d": "2", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(new Map([['a', 1], ['b', 2]]).get('b'));", "option_a": "'b'", "option_b": "undefined", "option_c": "1", "option_d": "2", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].at(0));", "option_a": "1", "option_b": "0", "option_c": "[1]", "option_d": "undefined", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(String.raw`Hello\\nWorld`);", "option_a": "Hello World", "option_b": "Hello\\nWorld", "option_c": "Hello\\\\nWorld", "option_d": "Error", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].reverse().toString());", "option_a": "[3,2,1]", "option_b": "321", "option_c": "3,2,1", "option_d": "1,2,3", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(typeof Symbol());", "option_a": "object", "option_b": "string", "option_c": "undefined", "option_d": "symbol", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([10, 9, 8].sort((a, b) => a - b));", "option_a": "[8, 9, 10]", "option_b": "[10, 9, 8]", "option_c": "[8, 10, 9]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number.MAX_SAFE_INTEGER === 2**53 - 1);", "option_a": "false", "option_b": "true", "option_c": "NaN", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.fromEntries([['a', 1], ['b', 2]]));", "option_a": "[['a',1],['b',2]]", "option_b": "undefined", "option_c": "{a: 1, b: 2}", "option_d": "Map", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(new WeakMap().has({}));", "option_a": "true", "option_b": "TypeError", "option_c": "undefined", "option_d": "false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].fill(0, 1));", "option_a": "[1, 0, 0]", "option_b": "[0, 0, 0]", "option_c": "[0, 2, 3]", "option_d": "[1, 2, 0]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log('abc'.includes('bc'));", "option_a": "false", "option_b": "true", "option_c": "1", "option_d": "'bc'", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(new Array(3).fill(null));", "option_a": "[3]", "option_b": "[null]", "option_c": "[null, null, null]", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Promise.resolve(42).then(v => v + 1));", "option_a": "43", "option_b": "42", "option_c": "undefined", "option_d": "Promise {<pending>}", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log('hello'.toUpperCase());", "option_a": "HELLO", "option_b": "hello", "option_c": "Hello", "option_d": "hELLO", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number.isFinite(Infinity));", "option_a": "true", "option_b": "false", "option_c": "Infinity", "option_d": "NaN", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].copyWithin(0, 2));", "option_a": "[1, 2, 3]", "option_b": "[2, 3, 3]", "option_c": "[3, 2, 3]", "option_d": "[3, 3, 3]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(Math.hypot(3, 4));", "option_a": "7", "option_b": "12", "option_c": "3.5", "option_d": "5", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].flatMap(x => [x, x * 2]));", "option_a": "[1, 2, 2, 4, 3, 6]", "option_b": "[[1,2],[2,4],[3,6]]", "option_c": "[2, 4, 6]", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Reflect.ownKeys({b: 2, a: 1}));", "option_a": "['a', 'b']", "option_b": "['b', 'a']", "option_c": "[2, 1]", "option_d": "undefined", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(new Intl.NumberFormat('en-US', {style: 'currency', currency: 'USD'}).format(1234));", "option_a": "1234", "option_b": "USD 1234", "option_c": "$1,234.00", "option_d": "1,234", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(queueMicrotask === undefined);", "option_a": "true", "option_b": "TypeError", "option_c": "null", "option_d": "false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log([1, 2, 3].entries().next().value);", "option_a": "[0, 1]", "option_b": "1", "option_c": "[1, 2, 3]", "option_d": "0", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(Number.parseFloat('3.14abc'));", "option_a": "NaN", "option_b": "3.14", "option_c": "3", "option_d": "'3.14'", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(Object.is(NaN, NaN));", "option_a": "false", "option_b": "undefined", "option_c": "true", "option_d": "NaN", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(new URLSearchParams('a=1&b=2').get('a'));", "option_a": "undefined", "option_b": "a=1", "option_c": "2", "option_d": "1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nconsole.log(new Date(0).toISOString());", "option_a": "1970-01-01T00:00:00.000Z", "option_b": "0", "option_c": "Invalid Date", "option_d": "null", "correct_option": "A"},
    {"question_text": "What is the output?\n\nconsole.log(JSON.stringify({a: undefined, b: 2}));", "option_a": "{\"a\":undefined,\"b\":2}", "option_b": "{\"b\":2}", "option_c": "null", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nconsole.log(new TextEncoder().encode('hi').length);", "option_a": "1", "option_b": "4", "option_c": "2", "option_d": "0", "correct_option": "C"},
    {"question_text": "What is the output?\n\nconsole.log(crypto.randomUUID().length);", "option_a": "32", "option_b": "16", "option_c": "64", "option_d": "36", "correct_option": "D"},
]
