JAVA_EXTRA_3 = [
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".replace('a', 'z'));", "option_a": "zbc", "option_b": "abc", "option_c": "azc", "option_d": "abz", "correct_option": "A"},
    {"question_text": "What is the return type of Stream.collect(Collectors.toList())?", "option_a": "Stream<T>", "option_b": "List<T>", "option_c": "Collection<T>", "option_d": "Set<T>", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".toUpperCase().charAt(1));", "option_a": "A", "option_b": "b", "option_c": "B", "option_d": "c", "correct_option": "C"},
    {"question_text": "Which Java version introduced records?", "option_a": "Java 11", "option_b": "Java 14 (preview)", "option_c": "Java 8", "option_d": "Java 16 (standard)", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"Hello\" + '!');", "option_a": "Hello!", "option_b": "Hello33", "option_c": "Hello", "option_d": "Compilation error", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(3 & 5);", "option_a": "35", "option_b": "1", "option_c": "7", "option_d": "8", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(3 | 5);", "option_a": "1", "option_b": "35", "option_c": "7", "option_d": "8", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(3 ^ 5);", "option_a": "1", "option_b": "7", "option_c": "35", "option_d": "6", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"java\".indexOf('v'));", "option_a": "2", "option_b": "3", "option_c": "1", "option_d": "-1", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(10 << 1);", "option_a": "10", "option_b": "20", "option_c": "5", "option_d": "1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(Arrays.toString(new int[]{3,1,2}));", "option_a": "int[]@hash", "option_b": "312", "option_c": "[3, 1, 2]", "option_d": "[1, 2, 3]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(10 >> 1);", "option_a": "10", "option_b": "20", "option_c": "1", "option_d": "5", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".concat(\"def\"));", "option_a": "abcdef", "option_b": "abc def", "option_c": "abc", "option_d": "def", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(1,2,3).stream().limit(2).toList());", "option_a": "[1, 2, 3]", "option_b": "[1, 2]", "option_c": "[2, 3]", "option_d": "2", "correct_option": "B"},
    {"question_text": "Which interface does HashMap implement?", "option_a": "Collection", "option_b": "List", "option_c": "Map", "option_d": "Set", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(Boolean.parseBoolean(\"yes\"));", "option_a": "true", "option_b": "yes", "option_c": "1", "option_d": "false", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(Boolean.parseBoolean(\"true\"));", "option_a": "true", "option_b": "false", "option_c": "1", "option_d": "TRUE", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"Hello\".substring(2));", "option_a": "He", "option_b": "llo", "option_c": "lo", "option_d": "l", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(String.valueOf(null).length());", "option_a": "NullPointerException", "option_b": "0", "option_c": "4", "option_d": "null", "correct_option": "C"},
    {"question_text": "Which method checks if a collection is empty?", "option_a": "size() == 0", "option_b": "length() == 0", "option_c": "isNull()", "option_d": "isEmpty()", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(Integer.compare(5, 3));", "option_a": "1", "option_b": "-1", "option_c": "0", "option_d": "2", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(new StringBuilder().capacity());", "option_a": "0", "option_b": "16", "option_c": "10", "option_d": "32", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(Collections.singletonList(42).get(0));", "option_a": "[42]", "option_b": "null", "option_c": "42", "option_d": "UnsupportedOperationException", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"hello world\".indexOf(\"world\"));", "option_a": "5", "option_b": "4", "option_c": "11", "option_d": "6", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".isEmpty());", "option_a": "false", "option_b": "true", "option_c": "0", "option_d": "null", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"\".isEmpty());", "option_a": "false", "option_b": "true", "option_c": "NullPointerException", "option_d": "0", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"  \".isBlank());", "option_a": "false", "option_b": "\" \"", "option_c": "true", "option_d": "NullPointerException", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(\" hello \".strip());", "option_a": "hello ", "option_b": " hello", "option_c": " hello ", "option_d": "hello", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".repeat(0));", "option_a": "\"\" (empty string)", "option_b": "abc", "option_c": "null", "option_d": "0", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(1, 2, 3).contains(2));", "option_a": "2", "option_b": "true", "option_c": "false", "option_d": "1", "correct_option": "B"},
    {"question_text": "What is the default capacity of an ArrayList?", "option_a": "0", "option_b": "16", "option_c": "10", "option_d": "100", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(Map.of(\"a\", 1, \"b\", 2).getOrDefault(\"c\", -1));", "option_a": "null", "option_b": "0", "option_c": "2", "option_d": "-1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"Hello\".toLowerCase());", "option_a": "hello", "option_b": "HELLO", "option_c": "Hello", "option_d": "hELLO", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(\"a\", \"b\", \"c\").indexOf(\"b\"));", "option_a": "b", "option_b": "1", "option_c": "2", "option_d": "0", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(Stream.empty().count());", "option_a": "null", "option_b": "Optional.empty", "option_c": "0", "option_d": "NoSuchElementException", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(Objects.requireNonNullElse(null, \"default\"));", "option_a": "null", "option_b": "NullPointerException", "option_c": "Optional.empty", "option_d": "default", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"Java\".length());", "option_a": "4", "option_b": "3", "option_c": "5", "option_d": "Java", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(String.join(\" \", \"Hello\", \"World\"));", "option_a": "HelloWorld", "option_b": "Hello World", "option_c": "Hello, World", "option_d": "[Hello, World]", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(5, 3, 1).stream().min(Integer::compare).get());", "option_a": "5", "option_b": "3", "option_c": "1", "option_d": "Optional[1]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(5, 3, 1).stream().max(Integer::compare).get());", "option_a": "1", "option_b": "3", "option_c": "Optional[5]", "option_d": "5", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".startsWith(\"ab\"));", "option_a": "true", "option_b": "false", "option_c": "ab", "option_d": "1", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"abc\".startsWith(\"bc\"));", "option_a": "true", "option_b": "false", "option_c": "bc", "option_d": "0", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(Math.min(5, 3));", "option_a": "5", "option_b": "8", "option_c": "3", "option_d": "2", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(Math.max(5, 3));", "option_a": "3", "option_b": "8", "option_c": "2", "option_d": "5", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"hello\".toUpperCase());", "option_a": "HELLO", "option_b": "hello", "option_c": "Hello", "option_d": "hELLO", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"ABC\".toLowerCase());", "option_a": "ABC", "option_b": "abc", "option_c": "Abc", "option_d": "aBC", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"  hello  \".trim());", "option_a": "hello  ", "option_b": "  hello", "option_c": "hello", "option_d": "  hello  ", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(Integer.parseInt(\"FF\", 16));", "option_a": "FF", "option_b": "15", "option_c": "0xFF", "option_d": "255", "correct_option": "D"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(1, 2, 3).size());", "option_a": "3", "option_b": "0", "option_c": "2", "option_d": "[1,2,3]", "correct_option": "A"},
    {"question_text": "What is the output?\n\nSystem.out.println(List.of(1, 2, 3).get(1));", "option_a": "1", "option_b": "2", "option_c": "3", "option_d": "0", "correct_option": "B"},
    {"question_text": "What is the output?\n\nSystem.out.println(Set.of(1, 2, 3).size());", "option_a": "0", "option_b": "2", "option_c": "3", "option_d": "1", "correct_option": "C"},
    {"question_text": "What is the output?\n\nSystem.out.println(\"Hello\".charAt(0));", "option_a": "e", "option_b": "Hello", "option_c": "0", "option_d": "H", "correct_option": "D"},
]
