PYTHON_EXTRA_3 = [
    {"question_text": "What is the output?\n\nprint(type(...))", "option_a": "<class 'ellipsis'>", "option_b": "Ellipsis", "option_c": "SyntaxError", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('hello'[10:])", "option_a": "IndexError", "option_b": "''", "option_c": "None", "option_d": "'hello'", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint({} == False)", "option_a": "True", "option_b": "SyntaxError", "option_c": "False", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(len(set([1,1,2,2,3,3])))", "option_a": "6", "option_b": "2", "option_c": "1", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(0.1 + 0.2 == 0.3)", "option_a": "False", "option_b": "True", "option_c": "0.3", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(type(1+2j).__name__)", "option_a": "int", "option_b": "complex", "option_c": "float", "option_d": "number", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(['a','b','c'].count('a'))", "option_a": "0", "option_b": "True", "option_c": "1", "option_d": "'a'", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(int('10', 8))", "option_a": "10", "option_b": "80", "option_c": "18", "option_d": "8", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint([].append(1))", "option_a": "None", "option_b": "[1]", "option_c": "1", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('hello'.index('e'))", "option_a": "0", "option_b": "1", "option_c": "2", "option_d": "-1", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(len(''))", "option_a": "1", "option_b": "None", "option_c": "0", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(type(frozenset()))", "option_a": "set", "option_b": "tuple", "option_c": "list", "option_d": "<class 'frozenset'>", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('abcde'[::2])", "option_a": "ace", "option_b": "bd", "option_c": "abcde", "option_d": "ae", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(zip)", "option_a": "zip", "option_b": "<class 'zip'>", "option_c": "TypeError", "option_d": "None", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list(filter(lambda x: x>2, [1,2,3,4])))", "option_a": "[1,2]", "option_b": "[2,3,4]", "option_c": "[3, 4]", "option_d": "[4]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(2 == 2.0)", "option_a": "False", "option_b": "2", "option_c": "TypeError", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(bool(''))", "option_a": "False", "option_b": "True", "option_c": "''", "option_d": "None", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(bool(' '))", "option_a": "False", "option_b": "True", "option_c": "' '", "option_d": "None", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint([1,2,3][1:1])", "option_a": "[1]", "option_b": "[2]", "option_c": "[]", "option_d": "[1,2]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(type(1,))", "option_a": "tuple", "option_b": "int", "option_c": "SyntaxError", "option_d": "<class 'int'>", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint((1,) + (2,))", "option_a": "(1, 2)", "option_b": "(3,)", "option_c": "3", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(list(range(0)))", "option_a": "[0]", "option_b": "[]", "option_c": "0", "option_d": "range(0)", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('a' * -1)", "option_a": "-a", "option_b": "ValueError", "option_c": "''", "option_d": "None", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint({1: 'a', 2: 'b'}.items())", "option_a": "[(1,'a'),(2,'b')]", "option_b": "[1,2]", "option_c": "['a','b']", "option_d": "dict_items([(1, 'a'), (2, 'b')])", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(any([]))", "option_a": "False", "option_b": "True", "option_c": "[]", "option_d": "None", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(all([]))", "option_a": "False", "option_b": "True", "option_c": "[]", "option_d": "None", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(0 or 'hello')", "option_a": "0", "option_b": "True", "option_c": "hello", "option_d": "False", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint('hello' and 'world')", "option_a": "hello", "option_b": "True", "option_c": "helloworld", "option_d": "world", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('' or 'default')", "option_a": "default", "option_b": "''", "option_c": "False", "option_d": "None", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(1 or 2)", "option_a": "2", "option_b": "1", "option_c": "True", "option_d": "3", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(0 and 'hello')", "option_a": "'hello'", "option_b": "False", "option_c": "0", "option_d": "None", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(len(b'\\x00\\x01\\x02'))", "option_a": "6", "option_b": "12", "option_c": "0", "option_d": "3", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint({1, 2, 3}.issuperset({1, 2}))", "option_a": "True", "option_b": "False", "option_c": "{1,2}", "option_d": "{3}", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('hello'.upper().lower())", "option_a": "HELLO", "option_b": "hello", "option_c": "Hello", "option_d": "hELLO", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(type(range(5)).__name__)", "option_a": "list", "option_b": "generator", "option_c": "range", "option_d": "iterator", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(1_000_000)", "option_a": "1000000", "option_b": "1_000_000", "option_c": "SyntaxError", "option_d": "1000000", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(len({True: 1, 1: 2, 1.0: 3}))", "option_a": "1", "option_b": "3", "option_c": "2", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint({True: 1, 1: 2, 1.0: 3}[True])", "option_a": "1", "option_b": "3", "option_c": "True", "option_d": "KeyError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('abc'.translate(str.maketrans('abc', 'xyz')))", "option_a": "abc", "option_b": "abcxyz", "option_c": "xyz", "option_d": "xyzabc", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint((lambda *args: len(args))(1, 2, 3, 4))", "option_a": "1", "option_b": "(1,2,3,4)", "option_c": "10", "option_d": "4", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(complex(0, 1) ** 2)", "option_a": "(-1+0j)", "option_b": "(0+2j)", "option_c": "1", "option_d": "(1+0j)", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('hello'.__class__.__name__)", "option_a": "object", "option_b": "str", "option_c": "string", "option_d": "text", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(list(reversed('abc')))", "option_a": "'cba'", "option_b": "['abc']", "option_c": "['c', 'b', 'a']", "option_d": "reversed", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(1 if True else 0)", "option_a": "True", "option_b": "0", "option_c": "False", "option_d": "1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(round(0.5))", "option_a": "0", "option_b": "1", "option_c": "0.5", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(round(1.5))", "option_a": "1", "option_b": "2", "option_c": "1.5", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(sorted('cba', reverse=True))", "option_a": "['a','b','c']", "option_b": "'cba'", "option_c": "['c', 'b', 'a']", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(type(open))", "option_a": "function", "option_b": "file", "option_c": "io", "option_d": "<class 'builtin_function_or_method'>", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(callable(print))", "option_a": "True", "option_b": "False", "option_c": "print", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(callable(42))", "option_a": "True", "option_b": "False", "option_c": "42", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(len(b'hello'))", "option_a": "10", "option_b": "0", "option_c": "5", "option_d": "hello", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(hash(1) == hash(1.0))", "option_a": "False", "option_b": "1", "option_c": "TypeError", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(sum([True, True, False, True]))", "option_a": "3", "option_b": "True", "option_c": "4", "option_d": "1", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(str([1,2,3]))", "option_a": "123", "option_b": "[1, 2, 3]", "option_c": "(1,2,3)", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint({1,2,3}.symmetric_difference({2,3,4}))", "option_a": "{2,3}", "option_b": "{1,2,3,4}", "option_c": "{1, 4}", "option_d": "set()", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(bin(-3))", "option_a": "11", "option_b": "0b11", "option_c": "-0b10", "option_d": "-0b11", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(repr('hello'))", "option_a": "'hello'", "option_b": "hello", "option_c": "repr(hello)", "option_d": "<str>", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(type(None))", "option_a": "None", "option_b": "<class 'NoneType'>", "option_c": "null", "option_d": "type", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(min([], default=0))", "option_a": "ValueError", "option_b": "None", "option_c": "0", "option_d": "[]", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(max([], default=-1))", "option_a": "ValueError", "option_b": "0", "option_c": "None", "option_d": "-1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(list(map(int, '123')))", "option_a": "[1, 2, 3]", "option_b": "[123]", "option_c": "['1','2','3']", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(isinstance(True, bool))", "option_a": "False", "option_b": "True", "option_c": "bool", "option_d": "TypeError", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(issubclass(bool, int))", "option_a": "False", "option_b": "int", "option_c": "True", "option_d": "TypeError", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(hasattr('hello', '__len__'))", "option_a": "False", "option_b": "5", "option_c": "'__len__'", "option_d": "True", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(getattr('hello', 'upper')())", "option_a": "HELLO", "option_b": "hello", "option_c": "upper", "option_d": "AttributeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(abs(complex(3, 4)))", "option_a": "3", "option_b": "5.0", "option_c": "4", "option_d": "7", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint('{:>10}'.format('hi'))", "option_a": "'hi        '", "option_b": "'    hi    '", "option_c": "'        hi'", "option_d": "'hi'", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(f'{3.14159:.2f}')", "option_a": "3", "option_b": "3.1", "option_c": "3.141", "option_d": "3.14", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint('abcabc'.replace('b', 'x', 1))", "option_a": "axcabc", "option_b": "axcaxc", "option_c": "abcaxc", "option_d": "xxcxxc", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint('hello world'.split('o'))", "option_a": "['hell', ' w', 'rld']", "option_b": "['hello', 'world']", "option_c": "['hell', 'w', 'rld']", "option_d": "['hello world']", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(len(dict.fromkeys(range(5))))", "option_a": "0", "option_b": "5", "option_c": "4", "option_d": "10", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(tuple(range(3)))", "option_a": "(3,)", "option_b": "[0,1,2]", "option_c": "(0, 1, 2)", "option_d": "range(3)", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(set(range(3)))", "option_a": "(0,1,2)", "option_b": "[0,1,2]", "option_c": "range(3)", "option_d": "{0, 1, 2}", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(object.__bases__)", "option_a": "()", "option_b": "(object,)", "option_c": "None", "option_d": "TypeError", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(int.__bases__)", "option_a": "()", "option_b": "(object,)", "option_c": "(int,)", "option_d": "(number,)", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(bool.__bases__)", "option_a": "(object,)", "option_b": "(bool,)", "option_c": "(int,)", "option_d": "(number,)", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint((1, 2, 3).count(2))", "option_a": "2", "option_b": "0", "option_c": "3", "option_d": "1", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint((1, 2, 3).index(3))", "option_a": "2", "option_b": "3", "option_c": "1", "option_d": "0", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(bytearray(b'abc')[0])", "option_a": "b'a'", "option_b": "97", "option_c": "'a'", "option_d": "0", "correct_option": "B"},
    {"question_text": "What is the output?\n\nprint(len({1: 'a', 2: 'b'}))", "option_a": "4", "option_b": "1", "option_c": "2", "option_d": "6", "correct_option": "C"},
    {"question_text": "What is the output?\n\nprint(list({1: 'a', 2: 'b'}))", "option_a": "['a', 'b']", "option_b": "[(1,'a'),(2,'b')]", "option_c": "[1, 2, 'a', 'b']", "option_d": "[1, 2]", "correct_option": "D"},
    {"question_text": "What is the output?\n\nprint(min('hello'))", "option_a": "'e'", "option_b": "'h'", "option_c": "'o'", "option_d": "'l'", "correct_option": "A"},
    {"question_text": "What is the output?\n\nprint(max('hello'))", "option_a": "'h'", "option_b": "'o'", "option_c": "'l'", "option_d": "'e'", "correct_option": "B"},
]
