"""add spending_category and booking_details to supers_coin_invoice

Revision ID: 021c53394a8c
Revises: 94a166a29dc3
Create Date: 2026-07-10 13:30:01.398609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021c53394a8c'
down_revision = '94a166a29dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supers_coin_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spending_category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('booking_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supers_coin_invoice', schema=None) as batch_op:
        batch_op.drop_column('booking_details')
        batch_op.drop_column('spending_category')

    # ### end Alembic commands ###
