"""add gift_card table

Revision ID: 46e6ca8b60e0
Revises: cb4f4d40102e
Create Date: 2026-02-14 15:00:53.129852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e6ca8b60e0'
down_revision = 'cb4f4d40102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('denomination', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_number_encrypted', sa.Text(), nullable=False),
    sa.Column('pin_encrypted', sa.Text(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=True),
    sa.Column('recipient_email', sa.String(length=150), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_card_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_card_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_card_status'))
        batch_op.drop_index(batch_op.f('ix_gift_card_brand'))

    op.drop_table('gift_card')
    # ### end Alembic commands ###
