"""Add interview_feedback table

Revision ID: 5ef55d936ae2
Revises: ef6c314d5ce2
Create Date: 2026-01-30 15:47:48.974338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef55d936ae2'
down_revision = 'ef6c314d5ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('communication_skills', sa.Integer(), nullable=False),
    sa.Column('technical_knowledge', sa.Integer(), nullable=False),
    sa.Column('problem_solving', sa.Integer(), nullable=False),
    sa.Column('cultural_fit', sa.Integer(), nullable=False),
    sa.Column('overall_impression', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_feedback')
    # ### end Alembic commands ###
