"""Add newsletter_subscribed to User

Revision ID: 8f17a9a63f7b
Revises: 8df91ae03166
Create Date: 2026-05-27 04:46:55.519232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f17a9a63f7b'
down_revision = '8df91ae03166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_subscribed', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('newsletter_subscribed')

    # ### end Alembic commands ###
