"""add paid_at to supers_coin_invoice

Revision ID: 94a166a29dc3
Revises: f4b2c8d9e101
Create Date: 2026-07-10 12:22:03.846730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a166a29dc3'
down_revision = 'f4b2c8d9e101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supers_coin_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supers_coin_invoice', schema=None) as batch_op:
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
