"""Initial migration after refactoring

Revision ID: a0d55b0b9cc2
Revises: 
Create Date: 2025-12-26 22:22:15.659999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d55b0b9cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emi_payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('emi_payment_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'emi_plan', ['plan_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Unpaid'::character varying"))

    with op.batch_alter_table('seller_inventory', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_inventory', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Unpaid'::character varying"))

    with op.batch_alter_table('emi_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('emi_payment_plan_id_fkey'), 'emi_plan', ['plan_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
