"""Add Interview and InterviewParticipant models for Google Meet scheduling

Revision ID: b7e9752b169b
Revises: 138e2cce99cd
Create Date: 2026-01-29 12:18:47.780870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e9752b169b'
down_revision = '138e2cce99cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_category_price', ['category', 'price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_category_price')

    # ### end Alembic commands ###
