"""add_category_to_mcq_questions

Revision ID: cb4f4d40102e
Revises: 6c587dda02b1
Create Date: 2026-02-09 23:21:21.893065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4f4d40102e'
down_revision = '6c587dda02b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcq_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_mcq_question_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcq_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcq_question_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
