"""add_inventory_rollback_request_table

Revision ID: e88696ba1bc6
Revises: bd09f410fc3e
Create Date: 2026-07-21 15:07:44.868035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88696ba1bc6'
down_revision = 'bd09f410fc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_rollback_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_inventory_id'], ['seller_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_rollback_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_rollback_request_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_rollback_request_request_date'), ['request_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_rollback_request_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_rollback_request_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_rollback_request_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_rollback_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_rollback_request_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_rollback_request_seller_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_rollback_request_request_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_rollback_request_request_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_rollback_request_product_id'))

    op.drop_table('inventory_rollback_request')
    # ### end Alembic commands ###
