"""add app feature table

Revision ID: ee85b95a4d7f
Revises: 1804475d361a
Create Date: 2026-04-18 08:55:42.275417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee85b95a4d7f'
down_revision = '1804475d361a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('android_app_release', schema=None) as batch_op:
        batch_op.alter_column('release_notes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('android_app_release', schema=None) as batch_op:
        batch_op.alter_column('release_notes',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('app_feature')
    # ### end Alembic commands ###
